# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json
default_language_version.python = "3.14"

[[repos]]
repo = "https://github.com/psf/black"
rev = "26.5.1"
hooks = [
  {
    id = "black",
  }
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.18"
hooks = [
  {
    id = "ruff",
    args = [
      "--fix",
      "--select=E,F,W,C,I,N,B,B9,S,ANN,ERA,A,C4,FA,LOG,INP,PYI,Q,RET,SIM,TC,PTH,DOC",
    ]
  }
]

[[repos]]
repo = "https://github.com/asottile/pyupgrade"
rev = "v3.21.2"
hooks = [
  {
    id = "pyupgrade",
    args = ["--py314-plus"]
  }
]

[[repos]]
repo = "https://github.com/PyCQA/isort"
rev = "8.0.1"
hooks = [
  {
    id = "isort",
    args = [
      "--profile=black",
    ]
  }
]
